Sprint 6
ClevertecFrontendLab/raNYnight pull request #6
Opened 2024-04-07 13:48 UTC by raNYnight

2024-04-07 13:51 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712497894/update-trainings-3_360x740.png)

2024-04-07 19:59 UTC, ValadzkoAliaksei requested changes

2024-04-07 19:59 UTC, ValadzkoAliaksei commented on src/common-types/modal.ts
> +    getDefaultTrainingsWarnModal = 'getDefaultTrainingsWarnModal',
github-pages   не открывается(

2024-04-07 20:01 UTC, raNYnight commented on src/common-types/modal.ts
> +    getDefaultTrainingsWarnModal = 'getDefaultTrainingsWarnModal',
Точно, забыл настроить. Завтра сделаю

2024-04-07 23:13 UTC, SergeyGlazun requested changes
![image](https://github.com/ClevertecFrontendLab/raNYnight/assets/70904466/d4afddca-a9ba-4ff8-8815-9a3b48a7304d)
при заходе в приложение будучи не авторизованным блокируеться ui и не редиректит на авторизацию

2024-04-08 06:54 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712559282/update-trainings-3_360x740.png)

2024-04-08 07:17 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712560620/update-trainings-3_360x740.png)

2024-04-08 07:23 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712561028/update-trainings-3_360x740.png)

2024-04-08 07:58 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712563097/update-trainings-3_360x740.png)

2024-04-08 08:08 UTC, SergeyGlazun requested changes
![image](https://github.com/ClevertecFrontendLab/raNYnight/assets/70904466/baf5fcd3-0bbc-4ab5-87ab-63b03d99ab1b)
проблема все еще актуально, проверти useEfect где нет зависимостей, летит куча запроссов, блочит ui

2024-04-08 08:29 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/raNYnight/assets/70904466/d14bb27f-0ca1-4800-8099-1890d3c9b591)
при добавлении нового упражнения без названия упражнения можно сохрнаить

2024-04-08 08:34 UTC, ValadzkoAliaksei requested changes

2024-04-08 08:34 UTC, ValadzkoAliaksei commented on src/common-types/modal.ts
> +    partyTrainingInviteModal = 'partyTrainingInviteModal',
![image](https://github.com/ClevertecFrontendLab/raNYnight/assets/61273546/98b2d892-2dd3-4c31-bb0f-8c03ab5258ee)
почему-то 2 раза летит запрос за тренировками после изменения (что успешного, что нет)

2024-04-08 10:26 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-04-08 10:38 UTC, raNYnight commented on src/components/highlighted-text/highlighted-text.tsx
> +    if (!textToHighlight || !initialText) {
Тогда TS ругается на последующее использование textToHighlight  и initialText

2024-04-08 10:40 UTC, raNYnight commented
@ValadzkoAliaksei  @SergeyGlazun Я поставил handler что если 403 ошибка (jwt неверный) то редиректит на auth и чистит ls. Но тогда тесты не проходят. На деплое всё работает сейчас. Замечания устранил

2024-04-08 10:41 UTC, raNYnight commented on src/common-types/modal.ts
> +    partyTrainingInviteModal = 'partyTrainingInviteModal',
У меня всегда 1 запрос летит и на деплое тоже. Хмм

2024-04-08 11:44 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-04-08 12:10 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712578224/update-trainings-3_360x740.png)

2024-04-08 12:46 UTC, ValadzkoAliaksei approved these changes

2024-04-08 13:07 UTC, SergeyGlazun requested changes
![image](https://github.com/ClevertecFrontendLab/raNYnight/assets/70904466/568d40f6-51e6-4bfb-9423-f58a7e24d622)
проблема все еще актуальна

2024-04-08 15:15 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712589307/update-trainings-3_360x740.png)

2024-04-08 16:09 UTC, SergeyGlazun requested changes
<img width="1476" alt="image" src="https://github.com/ClevertecFrontendLab/raNYnight/assets/70904466/86d692d7-f2c1-4a5a-a79f-842429bca9a4">
если добавить новое упражнение, проблема остается

2024-04-08 17:04 UTC, raNYnight commented
> <img alt="image" width="1476" src="https://private-user-images.githubusercontent.com/70904466/320568807-86d692d7-f2c1-4a5a-a79f-842429bca9a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTU1ODEsIm5iZiI6MTcxMjU5NTI4MSwicGF0aCI6Ii83MDkwNDQ2Ni8zMjA1Njg4MDctODZkNjkyZDctZjJjMS00YTVhLWE3OWYtODQyNDI5YmNhOWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE2NTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MjgxMjczYjkzOWY4MWNlMjdiYTgxZmZjODYwNDFkZGZiNDJjZjNlNTRkZmYyNTU3NzA2ZGYwNTJiOWQ3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dNHThjAXQwSA9Un6mwYTmIkF5UYAh_xwod7SGuVMD3s"> если добавить новое упражнение, проблема остается



> <img alt="image" width="1476" src="https://private-user-images.githubusercontent.com/70904466/320568807-86d692d7-f2c1-4a5a-a79f-842429bca9a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTU1ODEsIm5iZiI6MTcxMjU5NTI4MSwicGF0aCI6Ii83MDkwNDQ2Ni8zMjA1Njg4MDctODZkNjkyZDctZjJjMS00YTVhLWE3OWYtODQyNDI5YmNhOWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE2NTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MjgxMjczYjkzOWY4MWNlMjdiYTgxZmZjODYwNDFkZGZiNDJjZjNlNTRkZmYyNTU3NzA2ZGYwNTJiOWQ3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dNHThjAXQwSA9Un6mwYTmIkF5UYAh_xwod7SGuVMD3s"> если добавить новое упражнение, проблема остается

У меня не заполненные не отправлялись в такой ситуации. Я так на прошлых спринтах логику понял. 
Добавил испрвавления, что вообще нельзя отправить если есть пустое.

2024-04-08 17:06 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/raNYnight/1712595984/update-trainings-3_360x740.png)

2024-04-08 19:08 UTC, SergeyGlazun approved these changes

2024-04-08 19:09 UTC, merged